export const data = [
  {
    id: '1f3a9b2e-4c2a-4d6f-9a1b-0f2e5c7a8b11',
    title: 'Tabiatdan ilhomlangan fotosurat va qisqa izoh',
    image: 'https://picsum.photos/id/1015/600/400',
    date: '2025-09-10T14:30:00Z',
    messages: 12,
    description:
      'Tabiatdan ilhomlangan fotosurat va qisqa izoh. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '2a7c6d9f-8b34-41e2-a7c0-3d6f2b9e4c22',
    title: 'Shahar manzarasi — tun yoritilganda',
    image: 'https://picsum.photos/id/1027/600/400',
    date: '2025-08-28T09:15:00Z',
    messages: 5,
    description:
      'Shahar manzarasi — tun yoritilganda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '3b9d5c1a-6f77-4b2e-9c3a-5a8d4f0e5d33',
    title: 'Dengiz bo‘yida dam olish momentlari',
    image: 'https://picsum.photos/id/1039/600/400',
    date: '2025-07-03T18:00:00Z',
    messages: 27,
    description:
      'Dengiz bo‘yida dam olish momentlari. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '4c2e8f7b-1d90-4f5b-8a2d-6e9b1c3f7e44',
    title: 'Minimalist joylashuv va interyer tafsilotlari',
    image: 'https://picsum.photos/id/1043/600/400',
    date: '2025-06-12T12:45:00Z',
    messages: 3,
    description:
      'Minimalist joylashuv va interyer tafsilotlari. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '5d1f0a8c-2e11-42b7-b6c9-7f3a2d8e9f55',
    title: 'Erta tong — sokin atmosfera',
    image: 'https://picsum.photos/id/1056/600/400',
    date: '2025-05-01T07:20:00Z',
    messages: 0,
    description:
      'Erta tong — sokin atmosfera. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '6e7b3c2d-9a44-4f1e-8c5b-8a2d3f4b6g66',
    title: 'Festival va jonli musiqadan lavha',
    image: 'https://picsum.photos/id/1069/600/400',
    date: '2025-04-18T21:10:00Z',
    messages: 41,
    description:
      'Festival va jonli musiqadan lavha. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '7f8c9d0e-3b55-4a2c-9e7f-9b4c5d6e7h77',
    title: 'Gastronomik kecha — taomlar va taqdimotlar',
    image: 'https://picsum.photos/id/1074/600/400',
    date: '2025-03-30T16:05:00Z',
    messages: 8,
    description:
      'Gastronomik kecha — taomlar va taqdimotlar. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '8g9d0e1f-4c66-4b3d-0f8a-0c5d6e7f8i88',
    title: 'Ijodiy fotosessiya — rang-barang elementlar',
    image: 'https://picsum.photos/id/1084/600/400',
    date: '2025-02-14T11:00:00Z',
    messages: 14,
    description:
      'Ijodiy fotosessiya — rang-barang elementlar. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '1f3a9b2e-4c2a-4d6f-9a1b-0f2e5c7a8b11',
    title: 'Tabiatdan ilhomlangan fotosurat va qisqa izoh',
    image: 'https://picsum.photos/id/1015/600/400',
    date: '2025-09-10T14:30:00Z',
    messages: 12,
    description:
      'Tabiatdan ilhomlangan fotosurat va qisqa izoh. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '2a7c6d9f-8b34-41e2-a7c0-3d6f2b9e4c22',
    title: 'Shahar manzarasi — tun yoritilganda',
    image: 'https://picsum.photos/id/1027/600/400',
    date: '2025-08-28T09:15:00Z',
    messages: 5,
    description:
      'Shahar manzarasi — tun yoritilganda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '3b9d5c1a-6f77-4b2e-9c3a-5a8d4f0e5d33',
    title: 'Dengiz bo‘yida dam olish momentlari',
    image: 'https://picsum.photos/id/1039/600/400',
    date: '2025-07-03T18:00:00Z',
    messages: 27,
    description:
      'Dengiz bo‘yida dam olish momentlari. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '4c2e8f7b-1d90-4f5b-8a2d-6e9b1c3f7e44',
    title: 'Minimalist joylashuv va interyer tafsilotlari',
    image: 'https://picsum.photos/id/1043/600/400',
    date: '2025-06-12T12:45:00Z',
    messages: 3,
    description:
      'Minimalist joylashuv va interyer tafsilotlari. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '5d1f0a8c-2e11-42b7-b6c9-7f3a2d8e9f55',
    title: 'Erta tong — sokin atmosfera',
    image: 'https://picsum.photos/id/1056/600/400',
    date: '2025-05-01T07:20:00Z',
    messages: 0,
    description:
      'Erta tong — sokin atmosfera. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '6e7b3c2d-9a44-4f1e-8c5b-8a2d3f4b6g66',
    title: 'Festival va jonli musiqadan lavha',
    image: 'https://picsum.photos/id/1069/600/400',
    date: '2025-04-18T21:10:00Z',
    messages: 41,
    description:
      'Festival va jonli musiqadan lavha. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '7f8c9d0e-3b55-4a2c-9e7f-9b4c5d6e7h77',
    title: 'Gastronomik kecha — taomlar va taqdimotlar',
    image: 'https://picsum.photos/id/1074/600/400',
    date: '2025-03-30T16:05:00Z',
    messages: 8,
    description:
      'Gastronomik kecha — taomlar va taqdimotlar. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '8g9d0e1f-4c66-4b3d-0f8a-0c5d6e7f8i88',
    title: 'Ijodiy fotosessiya — rang-barang elementlar',
    image: 'https://picsum.photos/id/1084/600/400',
    date: '2025-02-14T11:00:00Z',
    messages: 14,
    description:
      'Ijodiy fotosessiya — rang-barang elementlar. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '1f3a9b2e-4c2a-4d6f-9a1b-0f2e5c7a8b11',
    title: 'Tabiatdan ilhomlangan fotosurat va qisqa izoh',
    image: 'https://picsum.photos/id/1015/600/400',
    date: '2025-09-10T14:30:00Z',
    messages: 12,
    description:
      'Tabiatdan ilhomlangan fotosurat va qisqa izoh. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '2a7c6d9f-8b34-41e2-a7c0-3d6f2b9e4c22',
    title: 'Shahar manzarasi — tun yoritilganda',
    image: 'https://picsum.photos/id/1027/600/400',
    date: '2025-08-28T09:15:00Z',
    messages: 5,
    description:
      'Shahar manzarasi — tun yoritilganda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '3b9d5c1a-6f77-4b2e-9c3a-5a8d4f0e5d33',
    title: 'Dengiz bo‘yida dam olish momentlari',
    image: 'https://picsum.photos/id/1039/600/400',
    date: '2025-07-03T18:00:00Z',
    messages: 27,
    description:
      'Dengiz bo‘yida dam olish momentlari. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '4c2e8f7b-1d90-4f5b-8a2d-6e9b1c3f7e44',
    title: 'Minimalist joylashuv va interyer tafsilotlari',
    image: 'https://picsum.photos/id/1043/600/400',
    date: '2025-06-12T12:45:00Z',
    messages: 3,
    description:
      'Minimalist joylashuv va interyer tafsilotlari. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '5d1f0a8c-2e11-42b7-b6c9-7f3a2d8e9f55',
    title: 'Erta tong — sokin atmosfera',
    image: 'https://picsum.photos/id/1056/600/400',
    date: '2025-05-01T07:20:00Z',
    messages: 0,
    description:
      'Erta tong — sokin atmosfera. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '6e7b3c2d-9a44-4f1e-8c5b-8a2d3f4b6g66',
    title: 'Festival va jonli musiqadan lavha',
    image: 'https://picsum.photos/id/1069/600/400',
    date: '2025-04-18T21:10:00Z',
    messages: 41,
    description:
      'Festival va jonli musiqadan lavha. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '7f8c9d0e-3b55-4a2c-9e7f-9b4c5d6e7h77',
    title: 'Gastronomik kecha — taomlar va taqdimotlar',
    image: 'https://picsum.photos/id/1074/600/400',
    date: '2025-03-30T16:05:00Z',
    messages: 8,
    description:
      'Gastronomik kecha — taomlar va taqdimotlar. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '8g9d0e1f-4c66-4b3d-0f8a-0c5d6e7f8i88',
    title: 'Ijodiy fotosessiya — rang-barang elementlar',
    image: 'https://picsum.photos/id/1084/600/400',
    date: '2025-02-14T11:00:00Z',
    messages: 14,
    description:
      'Ijodiy fotosessiya — rang-barang elementlar. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '1f3a9b2e-4c2a-4d6f-9a1b-0f2e5c7a8b11',
    title: 'Tabiatdan ilhomlangan fotosurat va qisqa izoh',
    image: 'https://picsum.photos/id/1015/600/400',
    date: '2025-09-10T14:30:00Z',
    messages: 12,
    description:
      'Tabiatdan ilhomlangan fotosurat va qisqa izoh. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '2a7c6d9f-8b34-41e2-a7c0-3d6f2b9e4c22',
    title: 'Shahar manzarasi — tun yoritilganda',
    image: 'https://picsum.photos/id/1027/600/400',
    date: '2025-08-28T09:15:00Z',
    messages: 5,
    description:
      'Shahar manzarasi — tun yoritilganda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '3b9d5c1a-6f77-4b2e-9c3a-5a8d4f0e5d33',
    title: 'Dengiz bo‘yida dam olish momentlari',
    image: 'https://picsum.photos/id/1039/600/400',
    date: '2025-07-03T18:00:00Z',
    messages: 27,
    description:
      'Dengiz bo‘yida dam olish momentlari. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '4c2e8f7b-1d90-4f5b-8a2d-6e9b1c3f7e44',
    title: 'Minimalist joylashuv va interyer tafsilotlari',
    image: 'https://picsum.photos/id/1043/600/400',
    date: '2025-06-12T12:45:00Z',
    messages: 3,
    description:
      'Minimalist joylashuv va interyer tafsilotlari. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '5d1f0a8c-2e11-42b7-b6c9-7f3a2d8e9f55',
    title: 'Erta tong — sokin atmosfera',
    image: 'https://picsum.photos/id/1056/600/400',
    date: '2025-05-01T07:20:00Z',
    messages: 0,
    description:
      'Erta tong — sokin atmosfera. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '6e7b3c2d-9a44-4f1e-8c5b-8a2d3f4b6g66',
    title: 'Festival va jonli musiqadan lavha',
    image: 'https://picsum.photos/id/1069/600/400',
    date: '2025-04-18T21:10:00Z',
    messages: 41,
    description:
      'Festival va jonli musiqadan lavha. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '7f8c9d0e-3b55-4a2c-9e7f-9b4c5d6e7h77',
    title: 'Gastronomik kecha — taomlar va taqdimotlar',
    image: 'https://picsum.photos/id/1074/600/400',
    date: '2025-03-30T16:05:00Z',
    messages: 8,
    description:
      'Gastronomik kecha — taomlar va taqdimotlar. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '8g9d0e1f-4c66-4b3d-0f8a-0c5d6e7f8i88',
    title: 'Ijodiy fotosessiya — rang-barang elementlar',
    image: 'https://picsum.photos/id/1084/600/400',
    date: '2025-02-14T11:00:00Z',
    messages: 14,
    description:
      'Ijodiy fotosessiya — rang-barang elementlar. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '1f3a9b2e-4c2a-4d6f-9a1b-0f2e5c7a8b11',
    title: 'Tabiatdan ilhomlangan fotosurat va qisqa izoh',
    image: 'https://picsum.photos/id/1015/600/400',
    date: '2025-09-10T14:30:00Z',
    messages: 12,
    description:
      'Tabiatdan ilhomlangan fotosurat va qisqa izoh. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '2a7c6d9f-8b34-41e2-a7c0-3d6f2b9e4c22',
    title: 'Shahar manzarasi — tun yoritilganda',
    image: 'https://picsum.photos/id/1027/600/400',
    date: '2025-08-28T09:15:00Z',
    messages: 5,
    description:
      'Shahar manzarasi — tun yoritilganda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '3b9d5c1a-6f77-4b2e-9c3a-5a8d4f0e5d33',
    title: 'Dengiz bo‘yida dam olish momentlari',
    image: 'https://picsum.photos/id/1039/600/400',
    date: '2025-07-03T18:00:00Z',
    messages: 27,
    description:
      'Dengiz bo‘yida dam olish momentlari. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '4c2e8f7b-1d90-4f5b-8a2d-6e9b1c3f7e44',
    title: 'Minimalist joylashuv va interyer tafsilotlari',
    image: 'https://picsum.photos/id/1043/600/400',
    date: '2025-06-12T12:45:00Z',
    messages: 3,
    description:
      'Minimalist joylashuv va interyer tafsilotlari. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '5d1f0a8c-2e11-42b7-b6c9-7f3a2d8e9f55',
    title: 'Erta tong — sokin atmosfera',
    image: 'https://picsum.photos/id/1056/600/400',
    date: '2025-05-01T07:20:00Z',
    messages: 0,
    description:
      'Erta tong — sokin atmosfera. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '6e7b3c2d-9a44-4f1e-8c5b-8a2d3f4b6g66',
    title: 'Festival va jonli musiqadan lavha',
    image: 'https://picsum.photos/id/1069/600/400',
    date: '2025-04-18T21:10:00Z',
    messages: 41,
    description:
      'Festival va jonli musiqadan lavha. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '7f8c9d0e-3b55-4a2c-9e7f-9b4c5d6e7h77',
    title: 'Gastronomik kecha — taomlar va taqdimotlar',
    image: 'https://picsum.photos/id/1074/600/400',
    date: '2025-03-30T16:05:00Z',
    messages: 8,
    description:
      'Gastronomik kecha — taomlar va taqdimotlar. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
  {
    id: '8g9d0e1f-4c66-4b3d-0f8a-0c5d6e7f8i88',
    title: 'Ijodiy fotosessiya — rang-barang elementlar',
    image: 'https://picsum.photos/id/1084/600/400',
    date: '2025-02-14T11:00:00Z',
    messages: 14,
    description:
      'Ijodiy fotosessiya — rang-barang elementlar. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga quo rerum ipsam quasi beatae quis iste dolorem eius dicta temporibus.',
  },
]

export const baseUrl = 'https://special-horn-8ee9415e94.strapiapp.com'
// 'https://strapi-backend-blog.onrender.com'
export const tabs = [
  {
    id: 'all',
    title: 'Все потоки',
  },
  {
    id: 'business',
    title: 'Разработка',
  },
  {
    id: 'registration',
    title: 'Администрирование',
  },
  {
    id: 'design',
    title: 'Дизайн',
  },
  {
    id: 'managment',
    title: 'Менеджмент',
  },
  {
    id: 'marketing',
    title: 'Маркетинг',
  },
  {
    id: 'travel',
    title: 'Научпоп',
  },
]

export const blogsPosts = {
  data: [
    {
      id: 1,
      documentId: 'd7a0k4kq4dk925ky6l1i1zlf',
      title: 'How to Improve Your Coding Skills',
      slug: 'how-to-improve-your-coding-skills',
      views: 23,
      description:
        'Here’s a clean, engaging blog post draft for your topic:\n\n---\n\n# How to Improve Your Coding Skills\n\nBecoming a better programmer is a journey, not a one-time achievement. Whether you’re a beginner or already have experience, consistent practice and smart learning strategies will help you grow faster. Here are some effective ways to improve your coding skills:\n\n---\n\n## 1. Code Every Day\n\nConsistency is key. Even 30–60 minutes of daily practice will build your problem-solving muscle and strengthen your understanding.\n👉 Tip: Solve small coding challenges or work on personal mini-projects regularly.\n\n---\n\n## 2. Work on Real Projects\n\nTheory is important, but practical projects teach you more.\n\n* Build apps, websites, or tools.\n* Contribute to open-source projects.\n* Recreate apps you use daily (like a to-do app or weather app).\n\n---\n\n## 3. Read and Understand Other People’s Code\n\nExplore GitHub repositories, tutorials, or open-source projects. Reading other developers’ code exposes you to new patterns, techniques, and problem-solving styles.\n\n---\n\n## 4. Learn Data Structures and Algorithms\n\nStrong fundamentals make you a more effective developer.\n\n* Start with arrays, objects, linked lists, and trees.\n* Practice algorithm problems on platforms like LeetCode, Codeforces, or HackerRank.\n\n---\n\n## 5. Participate in Coding Challenges\n\nJoin coding competitions and hackathons. They improve your speed, problem-solving, and teamwork skills under pressure.\n\n---\n\n## 6. Write Clean and Readable Code\n\nGood code isn’t just about solving problems—it’s about writing solutions others (and your future self) can understand.\n\n* Use meaningful variable names.\n* Add comments only where necessary.\n* Follow consistent formatting.\n\n---\n\n## 7. Keep Learning New Tools and Frameworks\n\nThe tech world evolves quickly. Stay updated by exploring new libraries, frameworks, and technologies relevant to your field (like React, Next.js, or Node.js for web developers).\n\n---\n\n## 8. Ask for Feedback and Do Code Reviews\n\nFeedback from experienced developers is priceless. Participate in code reviews, share your work, and learn from the mistakes others point out.\n\n---\n\n## 9. Teach What You Learn\n\nExplaining concepts to others (via blogs, videos, or mentoring) reinforces your knowledge and helps you discover gaps in your understanding.\n\n---\n\n## 10. Be Patient and Persistent\n\nImproving coding skills takes time. Don’t get discouraged if you don’t understand something right away. Every bug you fix and every project you complete makes you better.\n\n---\n\n✅ **Conclusion:**\nImproving your coding skills is about consistency, practice, and curiosity. Start small, keep building, learn from others, and never stop experimenting.\n\n---\n\nDo you want me to make this blog **short and motivational** (for beginners) or **longer with technical resources/links** for deeper learning?\n',
      createdAt: '2025-09-22T05:43:12.018Z',
      updatedAt: '2025-09-22T05:43:12.018Z',
      publishedAt: '2025-09-22T05:43:11.855Z',
      image: {
        id: 1,
        documentId: 'b5uyx6wh3lghvki6jczowshz',
        name: 'maxresdefault.jpg',
        alternativeText: null,
        caption: null,
        width: 1280,
        height: 720,
        formats: {
          large: {
            ext: '.jpg',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/large_maxresdefault_2524dd2e42.jpg',
            hash: 'large_maxresdefault_2524dd2e42',
            mime: 'image/jpeg',
            name: 'large_maxresdefault.jpg',
            path: null,
            size: 73.25,
            width: 1000,
            height: 563,
            sizeInBytes: 73246,
          },
          small: {
            ext: '.jpg',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/small_maxresdefault_2524dd2e42.jpg',
            hash: 'small_maxresdefault_2524dd2e42',
            mime: 'image/jpeg',
            name: 'small_maxresdefault.jpg',
            path: null,
            size: 28.54,
            width: 500,
            height: 281,
            sizeInBytes: 28540,
          },
          medium: {
            ext: '.jpg',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/medium_maxresdefault_2524dd2e42.jpg',
            hash: 'medium_maxresdefault_2524dd2e42',
            mime: 'image/jpeg',
            name: 'medium_maxresdefault.jpg',
            path: null,
            size: 50.17,
            width: 750,
            height: 422,
            sizeInBytes: 50171,
          },
          thumbnail: {
            ext: '.jpg',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/thumbnail_maxresdefault_2524dd2e42.jpg',
            hash: 'thumbnail_maxresdefault_2524dd2e42',
            mime: 'image/jpeg',
            name: 'thumbnail_maxresdefault.jpg',
            path: null,
            size: 10.23,
            width: 245,
            height: 138,
            sizeInBytes: 10227,
          },
        },
        hash: 'maxresdefault_2524dd2e42',
        ext: '.jpg',
        mime: 'image/jpeg',
        size: 94.59,
        url: 'https://special-horn-8ee9415e94.media.strapiapp.com/maxresdefault_2524dd2e42.jpg',
        previewUrl: null,
        provider: 'strapi-provider-upload-strapi-cloud',
        provider_metadata: null,
        createdAt: '2025-09-22T05:40:44.145Z',
        updatedAt: '2025-09-22T05:40:44.145Z',
        publishedAt: '2025-09-22T05:40:44.146Z',
      },
      author: {
        id: 1,
        documentId: 'ngl6xuhuzhwbszhud7n42aym',
        username: 'Jamshid',
        email: 'jamshid2002@gamil.com',
        provider: 'local',
        confirmed: true,
        blocked: false,
        createdAt: '2025-09-22T05:41:50.458Z',
        updatedAt: '2025-09-22T07:00:22.885Z',
        publishedAt: '2025-09-22T07:00:22.642Z',
      },
    },
    {
      id: 2,
      documentId: 'mx12788wgyfuwb6jenak20n6',
      title: 'Understanding Enums in Node.js: Features and Advantages',
      slug: 'understanding-enums-in-nodejs-features-and-advantages',
      views: 0,
      description:
        '# Understanding Enums in Node.js: Features and Advantages\n\n### Introduction\n\nWhen building applications in Node.js, developers often need to work with a set of predefined constant values. For example, user roles (`admin`, `editor`, `viewer`) or order statuses (`pending`, `completed`, `canceled`).\nInstead of using plain strings or numbers everywhere, **Enums** help us define and organize such values in a clean and structured way.\n\n---\n\n## What is an Enum?\n\nAn **Enum (short for “enumeration”)** is a special data structure that represents a group of constant values.\nAlthough JavaScript (and Node.js) doesn’t have built-in enums like TypeScript, we can implement them using:\n\n* **Objects**\n* **Frozen objects (`Object.freeze`)**\n* **TypeScript Enums** (if using TypeScript in Node.js projects)\n\n---\n\n## Example: Enum in Node.js with Objects\n\n```js\nconst UserRole = {\n  ADMIN: "admin",\n  EDITOR: "editor",\n  VIEWER: "viewer"\n};\n\nconsole.log(UserRole.ADMIN); // "admin"\n```\n\nTo make it immutable (unchangeable):\n\n```js\nconst UserRole = Object.freeze({\n  ADMIN: "admin",\n  EDITOR: "editor",\n  VIEWER: "viewer"\n});\n```\n\n---\n\n## Using Enums in TypeScript (Node.js + TS)\n\nTypeScript provides native support for enums:\n\n```ts\nenum OrderStatus {\n  Pending = "PENDING",\n  Completed = "COMPLETED",\n  Canceled = "CANCELED"\n}\n\nconsole.log(OrderStatus.Pending); // "PENDING"\n```\n\nThis is more powerful since TypeScript gives type safety and autocomplete.\n\n---\n\n## Features of Enums in Node.js\n\n✅ **Readability** – Code becomes more self-explanatory (no more “magic strings”).\n✅ **Maintainability** – Centralized place for all related constants.\n✅ **Type Safety (with TS)** – Prevents using invalid values.\n✅ **Immutability** – With `Object.freeze`, enums can’t be modified accidentally.\n✅ **Consistency** – Ensures same values are used across the project.\n\n---\n\n## Advantages of Using Enums\n\n1. **Cleaner Code**\n   Instead of repeating `"admin"` everywhere, we just use `UserRole.ADMIN`.\n\n2. **Fewer Bugs**\n   Typos like `"admn"` won’t break the code because enum values are fixed.\n\n3. **Easier Refactoring**\n   If `"admin"` changes to `"administrator"`, update it once in the enum.\n\n4. **Improved Collaboration**\n   Teams understand roles/statuses faster when they see enums instead of random strings.\n\n---\n\n## Conclusion\n\nEnums in Node.js help developers write **cleaner, safer, and more maintainable code**.\nEven though JavaScript doesn’t natively support enums, we can implement them using **objects and `Object.freeze`**, or switch to **TypeScript enums** for stronger type checking.\n\n👉 If your project is small, objects with constants are enough.\n👉 For larger applications, **TypeScript enums** are highly recommended.\n\n---\n\nAsilbek, xohlaysanmi men senga shu blogga **real-life example** qilib `UserRole` va `OrderStatus` bilan login/register system code yozib ko‘rsatib beray?\n',
      createdAt: '2025-09-22T07:20:35.574Z',
      updatedAt: '2025-09-22T07:20:35.574Z',
      publishedAt: '2025-09-22T07:20:35.545Z',
      image: {
        id: 4,
        documentId: 'wgezv7ff0dchijjd6ku5xz8y',
        name: 'enums.webp',
        alternativeText: null,
        caption: null,
        width: 1280,
        height: 720,
        formats: {
          large: {
            ext: '.webp',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/large_enums_4951e9ae42.webp',
            hash: 'large_enums_4951e9ae42',
            mime: 'image/webp',
            name: 'large_enums.webp',
            path: null,
            size: 3.51,
            width: 1000,
            height: 562,
            sizeInBytes: 3506,
          },
          small: {
            ext: '.webp',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/small_enums_4951e9ae42.webp',
            hash: 'small_enums_4951e9ae42',
            mime: 'image/webp',
            name: 'small_enums.webp',
            path: null,
            size: 1.56,
            width: 500,
            height: 281,
            sizeInBytes: 1560,
          },
          medium: {
            ext: '.webp',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/medium_enums_4951e9ae42.webp',
            hash: 'medium_enums_4951e9ae42',
            mime: 'image/webp',
            name: 'medium_enums.webp',
            path: null,
            size: 2.45,
            width: 750,
            height: 422,
            sizeInBytes: 2454,
          },
          thumbnail: {
            ext: '.webp',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/thumbnail_enums_4951e9ae42.webp',
            hash: 'thumbnail_enums_4951e9ae42',
            mime: 'image/webp',
            name: 'thumbnail_enums.webp',
            path: null,
            size: 0.73,
            width: 245,
            height: 138,
            sizeInBytes: 732,
          },
        },
        hash: 'enums_4951e9ae42',
        ext: '.webp',
        mime: 'image/webp',
        size: 5.35,
        url: 'https://special-horn-8ee9415e94.media.strapiapp.com/enums_4951e9ae42.webp',
        previewUrl: null,
        provider: 'strapi-provider-upload-strapi-cloud',
        provider_metadata: null,
        createdAt: '2025-09-22T07:20:35.072Z',
        updatedAt: '2025-09-22T07:20:35.072Z',
        publishedAt: '2025-09-22T07:20:35.074Z',
      },
      author: {
        id: 1,
        documentId: 'ngl6xuhuzhwbszhud7n42aym',
        username: 'Jamshid',
        email: 'jamshid2002@gamil.com',
        provider: 'local',
        confirmed: true,
        blocked: false,
        createdAt: '2025-09-22T05:41:50.458Z',
        updatedAt: '2025-09-22T07:00:22.885Z',
        publishedAt: '2025-09-22T07:00:22.642Z',
      },
    },
    {
      id: 3,
      documentId: 'cuy4mqa6epsm7nbzxzsf278d',
      title: 'AI Engineers: Who They Are and What They Do',
      slug: 'ai-engineers-who-they-are-and-what-they-do',
      views: 0,
      description:
        '### AI Engineers: Who They Are and What They Do\n\nArtificial Intelligence (AI) is no longer just a futuristic idea—it’s already part of our daily lives. From voice assistants like Siri and Alexa to recommendation systems on Netflix and YouTube, AI is everywhere. But have you ever wondered **who creates these intelligent systems?** That’s where **AI Engineers** come in.\n\n---\n\n## 👩‍💻 Who Are AI Engineers?\n\nAI Engineers are technology professionals who design, build, and deploy artificial intelligence systems. Their job is to make machines “think” and “learn” like humans by using **algorithms, machine learning models, and neural networks**.\n\nThey work at the intersection of **computer science, mathematics, and data science** to develop solutions that can:\n\n* Recognize images and speech\n* Analyze large datasets\n* Predict outcomes\n* Automate decision-making\n\n---\n\n## 🔑 Key Responsibilities of AI Engineers\n\nAI Engineers typically focus on:\n\n1. **Data Preparation** – Collecting, cleaning, and organizing data for training AI models.\n2. **Model Development** – Creating and testing machine learning algorithms.\n3. **Deployment** – Integrating AI models into applications and systems.\n4. **Optimization** – Improving accuracy, speed, and efficiency of models.\n5. **Research & Innovation** – Exploring new ways to apply AI in different industries.\n\n---\n\n## ⚡ Skills Required\n\nAn AI Engineer usually needs skills in:\n\n* **Programming Languages**: Python, R, Java, or C++\n* **Machine Learning Frameworks**: TensorFlow, PyTorch, Scikit-learn\n* **Mathematics & Statistics**: Linear algebra, probability, optimization\n* **Data Science**: Data analysis, visualization, and feature engineering\n* **Cloud & Deployment**: AWS, Azure, or Google Cloud for hosting AI models\n\n---\n\n## 🌍 Where Do AI Engineers Work?\n\nAI Engineers are in demand across multiple industries, such as:\n\n* **Healthcare**: AI for disease detection, drug discovery\n* **Finance**: Fraud detection, risk analysis, algorithmic trading\n* **E-commerce**: Personalized recommendations, chatbots\n* **Automotive**: Self-driving cars and smart navigation\n* **Robotics**: Intelligent machines for manufacturing and service industries\n\n---\n\n## 🚀 Why Become an AI Engineer?\n\n* **High demand** – Companies need AI experts more than ever.\n* **Great salaries** – AI Engineers are among the top-paid tech professionals.\n* **Impactful work** – You help shape the future of technology.\n\n---\n\n✅ **In short:** AI Engineers are the architects of intelligent systems. They combine coding, data science, and machine learning to create solutions that improve our everyday lives and shape the future of technology.\n\n---\n\nAsilbek, xohlaysanmi men senga shu postni **Strapi blog formatida (title, description, slug, content)** tayyorlab beray, to‘g‘ridan-to‘g‘ri API ga yuboradigan qilib?\n',
      createdAt: '2025-09-22T07:24:20.544Z',
      updatedAt: '2025-09-22T07:24:20.544Z',
      publishedAt: '2025-09-22T07:24:20.528Z',
      image: {
        id: 6,
        documentId: 'szmqvcg9zddlnjl3yk74ult7',
        name: 'ai.webp',
        alternativeText: null,
        caption: null,
        width: 1920,
        height: 1080,
        formats: {
          large: {
            ext: '.webp',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/large_ai_ec17c6742f.webp',
            hash: 'large_ai_ec17c6742f',
            mime: 'image/webp',
            name: 'large_ai.webp',
            path: null,
            size: 39.22,
            width: 1000,
            height: 562,
            sizeInBytes: 39216,
          },
          small: {
            ext: '.webp',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/small_ai_ec17c6742f.webp',
            hash: 'small_ai_ec17c6742f',
            mime: 'image/webp',
            name: 'small_ai.webp',
            path: null,
            size: 15.77,
            width: 500,
            height: 281,
            sizeInBytes: 15770,
          },
          medium: {
            ext: '.webp',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/medium_ai_ec17c6742f.webp',
            hash: 'medium_ai_ec17c6742f',
            mime: 'image/webp',
            name: 'medium_ai.webp',
            path: null,
            size: 27.23,
            width: 750,
            height: 422,
            sizeInBytes: 27230,
          },
          thumbnail: {
            ext: '.webp',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/thumbnail_ai_ec17c6742f.webp',
            hash: 'thumbnail_ai_ec17c6742f',
            mime: 'image/webp',
            name: 'thumbnail_ai.webp',
            path: null,
            size: 5.54,
            width: 245,
            height: 138,
            sizeInBytes: 5536,
          },
        },
        hash: 'ai_ec17c6742f',
        ext: '.webp',
        mime: 'image/webp',
        size: 94.45,
        url: 'https://special-horn-8ee9415e94.media.strapiapp.com/ai_ec17c6742f.webp',
        previewUrl: null,
        provider: 'strapi-provider-upload-strapi-cloud',
        provider_metadata: null,
        createdAt: '2025-09-22T07:24:20.043Z',
        updatedAt: '2025-09-22T07:24:20.043Z',
        publishedAt: '2025-09-22T07:24:20.043Z',
      },
      author: {
        id: 1,
        documentId: 'ngl6xuhuzhwbszhud7n42aym',
        username: 'Jamshid',
        email: 'jamshid2002@gamil.com',
        provider: 'local',
        confirmed: true,
        blocked: false,
        createdAt: '2025-09-22T05:41:50.458Z',
        updatedAt: '2025-09-22T07:00:22.885Z',
        publishedAt: '2025-09-22T07:00:22.642Z',
      },
    },
    {
      id: 5,
      documentId: 'wvyeb3rzvahs4a2ckw07x09c',
      title: 'Higher Order Functions in javascript.',
      slug: 'higher-order-functions-in-javascript',
      views: 0,
      description:
        ' # Higher Order Functions in JavaScript\n\nJavaScript’da funksiyalar oddiygina kod bo‘lagi emas, ular **birinchi darajali obyektlar** (“first-class citizens”). Bu degani – funksiyalarni o‘zgaruvchilarga saqlash, boshqa funksiyalarga argument sifatida berish yoki natija sifatida qaytarish mumkin.\n\nShu xususiyat tufayli **Higher Order Functions (HOF)** paydo bo‘ladi.\n\n---\n\n## Higher Order Function nima?\n\n👉 **Higher Order Function** – bu:\n\n* Funksiyani **argument sifatida qabul qiladigan** yoki\n* Funksiyani **natija sifatida qaytaradigan** funksiyadir.\n\nOddiy qilib aytganda: **funksiya ichida boshqa funksiyalar bilan ishlasa, u HOF bo‘ladi.**\n\n---\n\n## Misol 1: Funksiyani argument sifatida berish\n\n```javascript\nfunction greet(name) {\n  return `Hello, ${name}!`\n}\n\nfunction processUserInput(callback) {\n  const name = "Asilbek"\n  return callback(name)\n}\n\nconsole.log(processUserInput(greet)) \n// Output: Hello, Asilbek!\n```\n\nBu yerda `processUserInput` – **Higher Order Function**, chunki u boshqa funksiyani (`greet`) argument sifatida olmoqda.\n\n---\n\n## Misol 2: Funksiyani qaytarish\n\n```javascript\nfunction multiplier(factor) {\n  return function (number) {\n    return number * factor\n  }\n}\n\nconst double = multiplier(2)\nconsole.log(double(5)) // 10\n```\n\n👉 `multiplier` – HOF, chunki u boshqa funksiya qaytaradi.\n\n---\n\n## Amaliy Higher Order Functions:\n\nJavaScript’da ko‘p ishlatiladigan array metodlari aslida **HOF** hisoblanadi:\n\n### `map()`\n\n```javascript\nconst numbers = [1, 2, 3, 4]\nconst doubled = numbers.map(num => num * 2)\nconsole.log(doubled) // [2, 4, 6, 8]\n```\n\n### `filter()`\n\n```javascript\nconst numbers = [1, 2, 3, 4, 5]\nconst even = numbers.filter(num => num % 2 === 0)\nconsole.log(even) // [2, 4]\n```\n\n### `reduce()`\n\n```javascript\nconst numbers = [1, 2, 3, 4]\nconst sum = numbers.reduce((acc, num) => acc + num, 0)\nconsole.log(sum) // 10\n```\n\n---\n\n## Nega Higher Order Functions muhim?\n\n* **Kod qayta ishlatiladi** (reusable code).\n* **Chiroyli va ixcham yoziladi**.\n* **Functional programming** uslubini qo‘llash imkonini beradi.\n\n---\n\n## Xulosa\n\nHigher Order Functions – JavaScript’ni kuchli qiladigan asosiy konsepsiyalardan biri. `map`, `filter`, `reduce` kabi metodlar orqali ularni kundalik kodlashda ishlatamiz. Ular yordamida **kod soddaroq, moslashuvchan va tushunarli** bo‘ladi. ',
      createdAt: '2025-09-22T09:27:31.664Z',
      updatedAt: '2025-09-22T09:27:31.664Z',
      publishedAt: '2025-09-22T09:27:31.656Z',
      image: {
        id: 8,
        documentId: 's7eiuocyo15sjm4zxf043s0e',
        name: 'func.webp',
        alternativeText: null,
        caption: null,
        width: 1280,
        height: 720,
        formats: {
          large: {
            ext: '.webp',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/large_func_9e5a140a8f.webp',
            hash: 'large_func_9e5a140a8f',
            mime: 'image/webp',
            name: 'large_func.webp',
            path: null,
            size: 23.65,
            width: 1000,
            height: 562,
            sizeInBytes: 23646,
          },
          small: {
            ext: '.webp',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/small_func_9e5a140a8f.webp',
            hash: 'small_func_9e5a140a8f',
            mime: 'image/webp',
            name: 'small_func.webp',
            path: null,
            size: 10.49,
            width: 500,
            height: 281,
            sizeInBytes: 10490,
          },
          medium: {
            ext: '.webp',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/medium_func_9e5a140a8f.webp',
            hash: 'medium_func_9e5a140a8f',
            mime: 'image/webp',
            name: 'medium_func.webp',
            path: null,
            size: 17.8,
            width: 750,
            height: 422,
            sizeInBytes: 17800,
          },
          thumbnail: {
            ext: '.webp',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/thumbnail_func_9e5a140a8f.webp',
            hash: 'thumbnail_func_9e5a140a8f',
            mime: 'image/webp',
            name: 'thumbnail_func.webp',
            path: null,
            size: 4.47,
            width: 245,
            height: 138,
            sizeInBytes: 4470,
          },
        },
        hash: 'func_9e5a140a8f',
        ext: '.webp',
        mime: 'image/webp',
        size: 33.21,
        url: 'https://special-horn-8ee9415e94.media.strapiapp.com/func_9e5a140a8f.webp',
        previewUrl: null,
        provider: 'strapi-provider-upload-strapi-cloud',
        provider_metadata: null,
        createdAt: '2025-09-22T09:27:31.167Z',
        updatedAt: '2025-09-22T09:27:31.167Z',
        publishedAt: '2025-09-22T09:27:31.168Z',
      },
      author: {
        id: 2,
        documentId: 'c08gl5796b9a93tfk8ecrg1t',
        username: 'Akmaljon',
        email: 'akmal2002@gmail.com',
        provider: 'local',
        confirmed: true,
        blocked: false,
        createdAt: '2025-09-22T07:25:12.464Z',
        updatedAt: '2025-09-22T07:25:12.464Z',
        publishedAt: '2025-09-22T07:25:12.464Z',
      },
    },
    {
      id: 6,
      documentId: 'fy2jlbtc85388pez4cl2e0sl',
      title: 'Understanding Promises in JavaScript. A Comprehensive Guide',
      slug: 'understanding-promises-in-javascript-a-comprehensive-guide',
      views: 0,
      description:
        ' # Understanding Promises in JavaScript: A Comprehensive Guide\n\nJavaScript’da **asynchronous** vazifalarni bajarishda ko‘p ishlatiladigan konseptlardan biri – bu **Promise**.\n\nPromise – bu kelajakda **natija qaytarishi mumkin bo‘lgan operatsiyani** ifodalaydi: muvaffaqiyatli bo‘lsa qiymat qaytaradi, xatolik bo‘lsa esa error.\n\n---\n\n## Promise nima?\n\n👉 Promise – bu obyekt bo‘lib, u 3 ta holatdan birida bo‘lishi mumkin:\n\n1. **Pending** – kutilmoqda (hali natija yo‘q).\n2. **Fulfilled** – muvaffaqiyatli bajarildi (`resolve`).\n3. **Rejected** – xatolik yuz berdi (`reject`).\n\n---\n\n## Oddiy Promise misoli\n\n```javascript\nconst myPromise = new Promise((resolve, reject) => {\n  let success = true\n\n  if (success) {\n    resolve("✅ Data received!")\n  } else {\n    reject("❌ Something went wrong.")\n  }\n})\n\nmyPromise\n  .then(result => console.log(result)) \n  .catch(error => console.error(error))\n```\n\n---\n\n## `then()`, `catch()`, va `finally()`\n\n* **then()** → muvaffaqiyatli natija qaytarsa ishlaydi.\n* **catch()** → xatolik bo‘lsa ishlaydi.\n* **finally()** → natijadan qat’i nazar ishlaydi.\n\n```javascript\nfetch("https://jsonplaceholder.typicode.com/posts/1")\n  .then(response => response.json())\n  .then(data => console.log(data))\n  .catch(err => console.error("Error:", err))\n  .finally(() => console.log("Request finished"))\n```\n\n---\n\n## Promise Chaining\n\nBir nechta `then()` larni ketma-ket ulash mumkin:\n\n```javascript\nnew Promise(resolve => resolve(2))\n  .then(num => num * 2)   // 4\n  .then(num => num * 3)   // 12\n  .then(num => console.log(num)) // 12\n```\n\n---\n\n## `Promise.all()`\n\nBir nechta promise parallel bajarilishi uchun ishlatiladi.\n\n```javascript\nconst p1 = Promise.resolve("Hello")\nconst p2 = Promise.resolve("World")\n\nPromise.all([p1, p2]).then(values => {\n  console.log(values) // ["Hello", "World"]\n})\n```\n\n---\n\n## `Promise.race()`\n\nFaqat eng birinchi bajarilgan promise qaytariladi.\n\n```javascript\nconst p1 = new Promise(resolve => setTimeout(() => resolve("One"), 2000))\nconst p2 = new Promise(resolve => setTimeout(() => resolve("Two"), 1000))\n\nPromise.race([p1, p2]).then(value => console.log(value)) \n// Output: "Two"\n```\n\n---\n\n## Async/Await bilan Promises\n\n`async/await` – bu Promiseni yanada **tushunarli va toza sintaksis** bilan yozish usuli.\n\n```javascript\nasync function getData() {\n  try {\n    const response = await fetch("https://jsonplaceholder.typicode.com/posts/1")\n    const data = await response.json()\n    console.log(data)\n  } catch (error) {\n    console.error("Error:", error)\n  } finally {\n    console.log("Request finished")\n  }\n}\n\ngetData()\n```\n\n---\n\n## Xulosa\n\n* Promise – **asynchronous vazifalarni boshqarish** uchun juda qulay vosita.\n* `then`, `catch`, `finally` – natijani boshqarishda ishlatiladi.\n* `Promise.all`, `Promise.race` – parallel vazifalar uchun.\n* `async/await` – Promiseni soddalashtiradi va kodni o‘qishni osonlashtiradi. ',
      createdAt: '2025-09-22T09:30:41.033Z',
      updatedAt: '2025-09-22T09:30:41.033Z',
      publishedAt: '2025-09-22T09:30:41.024Z',
      image: {
        id: 9,
        documentId: 'z7ydgpp1m9nbjk568luei713',
        name: 'promise.webp',
        alternativeText: null,
        caption: null,
        width: 2360,
        height: 1380,
        formats: {
          large: {
            ext: '.webp',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/large_promise_8308bd933d.webp',
            hash: 'large_promise_8308bd933d',
            mime: 'image/webp',
            name: 'large_promise.webp',
            path: null,
            size: 10.86,
            width: 1000,
            height: 585,
            sizeInBytes: 10862,
          },
          small: {
            ext: '.webp',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/small_promise_8308bd933d.webp',
            hash: 'small_promise_8308bd933d',
            mime: 'image/webp',
            name: 'small_promise.webp',
            path: null,
            size: 5.28,
            width: 500,
            height: 292,
            sizeInBytes: 5284,
          },
          medium: {
            ext: '.webp',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/medium_promise_8308bd933d.webp',
            hash: 'medium_promise_8308bd933d',
            mime: 'image/webp',
            name: 'medium_promise.webp',
            path: null,
            size: 7.96,
            width: 750,
            height: 439,
            sizeInBytes: 7958,
          },
          thumbnail: {
            ext: '.webp',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/thumbnail_promise_8308bd933d.webp',
            hash: 'thumbnail_promise_8308bd933d',
            mime: 'image/webp',
            name: 'thumbnail_promise.webp',
            path: null,
            size: 2.42,
            width: 245,
            height: 143,
            sizeInBytes: 2416,
          },
        },
        hash: 'promise_8308bd933d',
        ext: '.webp',
        mime: 'image/webp',
        size: 27.27,
        url: 'https://special-horn-8ee9415e94.media.strapiapp.com/promise_8308bd933d.webp',
        previewUrl: null,
        provider: 'strapi-provider-upload-strapi-cloud',
        provider_metadata: null,
        createdAt: '2025-09-22T09:30:40.473Z',
        updatedAt: '2025-09-22T09:30:40.473Z',
        publishedAt: '2025-09-22T09:30:40.473Z',
      },
      author: {
        id: 2,
        documentId: 'c08gl5796b9a93tfk8ecrg1t',
        username: 'Akmaljon',
        email: 'akmal2002@gmail.com',
        provider: 'local',
        confirmed: true,
        blocked: false,
        createdAt: '2025-09-22T07:25:12.464Z',
        updatedAt: '2025-09-22T07:25:12.464Z',
        publishedAt: '2025-09-22T07:25:12.464Z',
      },
    },
    {
      id: 7,
      documentId: 'tcop21ba29lqmcamsq0prmtp',
      title: 'Mastering JavaScript Classes: A Comprehensive Guide',
      slug: 'mastering-javascript-classes-a-comprehensive-guide',
      views: 0,
      description:
        '# Mastering JavaScript Classes: A Comprehensive Guide\n\nJavaScript’da **class** – bu **object yaratish uchun shablon**.\nES6’dan boshlab, `class` sintaksisi joriy qilindi va u **OOP (Object-Oriented Programming)** uslubini soddaroq yozishga imkon beradi.\n\n---\n\n## Class nima?\n\nClass – bu:\n\n* **Property (xususiyatlar)**\n* **Method (funksiyalar)**\n  ni bir joyga jamlagan obyekt tuzilmasi.\n\nOddiy qilib aytganda: **object uchun blueprint**.\n\n---\n\n## Oddiy Class yaratish\n\n```javascript\nclass Person {\n  constructor(name, age) {\n    this.name = name\n    this.age = age\n  }\n\n  greet() {\n    console.log(`Hello, my name is ${this.name} and I\'m ${this.age} years old.`)\n  }\n}\n\nconst user = new Person("Asilbek", 23)\nuser.greet()\n// Output: Hello, my name is Asilbek and I\'m 23 years old.\n```\n\n---\n\n## Classda Constructor\n\n* `constructor()` – yangi obyekt yaratilganda avtomatik ishlaydi.\n* Unda obyektning boshlang‘ich qiymatlari o‘rnatiladi.\n\n---\n\n## Class Methods\n\nMetodlar class ichida yoziladi va obyektga tegishli bo‘ladi.\n\n```javascript\nclass Calculator {\n  add(a, b) {\n    return a + b\n  }\n  multiply(a, b) {\n    return a * b\n  }\n}\n\nconst calc = new Calculator()\nconsole.log(calc.add(2, 3))      // 5\nconsole.log(calc.multiply(2, 3)) // 6\n```\n\n---\n\n## Inheritance (Meros olish)\n\nBir class boshqa classdan xususiyat va metodlarni **olishi** mumkin.\n\n```javascript\nclass Animal {\n  speak() {\n    console.log("Animal makes a sound")\n  }\n}\n\nclass Dog extends Animal {\n  speak() {\n    console.log("Dog barks")\n  }\n}\n\nconst dog = new Dog()\ndog.speak() // Dog barks\n```\n\n---\n\n## `super` kalit so‘zi\n\nChild class ichida **parent class constructor/metodiga murojaat qilish** uchun ishlatiladi.\n\n```javascript\nclass Vehicle {\n  constructor(type) {\n    this.type = type\n  }\n}\n\nclass Car extends Vehicle {\n  constructor(type, brand) {\n    super(type) // parent constructor chaqirilmoqda\n    this.brand = brand\n  }\n}\n\nconst car = new Car("Car", "BMW")\nconsole.log(car.type, car.brand) // Car BMW\n```\n\n---\n\n## Getter va Setter\n\nProperty’larni boshqarish uchun maxsus metodlar.\n\n```javascript\nclass User {\n  constructor(name) {\n    this._name = name\n  }\n\n  get name() {\n    return this._name\n  }\n\n  set name(newName) {\n    this._name = newName\n  }\n}\n\nconst u = new User("Ali")\nconsole.log(u.name) // Ali\nu.name = "Vali"\nconsole.log(u.name) // Vali\n```\n\n---\n\n## Static Methods\n\nClassga tegishli metodlar bo‘lib, obyekt yaratmasdan chaqiriladi.\n\n```javascript\nclass MathUtils {\n  static square(x) {\n    return x * x\n  }\n}\n\nconsole.log(MathUtils.square(5)) // 25\n```\n\n---\n\n## Xulosa\n\n* **Class** – obyekt yaratish uchun blueprint.\n* `constructor` – boshlang‘ich qiymatlarni belgilash uchun.\n* `extends` – meros olish imkonini beradi.\n* `super` – parent class’ga murojaat qilish uchun.\n* `getter/setter` – property’larni boshqaradi.\n* `static` – obyekt yaratmasdan metodlarni chaqirish uchun.\n\nJavaScript classlari yordamida kodni **tartibli, qayta ishlatiladigan va object-oriented** qilish mumkin. ',
      createdAt: '2025-09-22T09:37:23.720Z',
      updatedAt: '2025-09-22T09:37:23.720Z',
      publishedAt: '2025-09-22T09:37:23.710Z',
      image: {
        id: 10,
        documentId: 'ct16t70b2apbe0j24aaxb1b4',
        name: 'javasript.webp',
        alternativeText: null,
        caption: null,
        width: 1280,
        height: 710,
        formats: {
          large: {
            ext: '.webp',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/large_javasript_f1475e45fe.webp',
            hash: 'large_javasript_f1475e45fe',
            mime: 'image/webp',
            name: 'large_javasript.webp',
            path: null,
            size: 16.36,
            width: 1000,
            height: 555,
            sizeInBytes: 16356,
          },
          small: {
            ext: '.webp',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/small_javasript_f1475e45fe.webp',
            hash: 'small_javasript_f1475e45fe',
            mime: 'image/webp',
            name: 'small_javasript.webp',
            path: null,
            size: 6.98,
            width: 500,
            height: 277,
            sizeInBytes: 6982,
          },
          medium: {
            ext: '.webp',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/medium_javasript_f1475e45fe.webp',
            hash: 'medium_javasript_f1475e45fe',
            mime: 'image/webp',
            name: 'medium_javasript.webp',
            path: null,
            size: 11.92,
            width: 750,
            height: 416,
            sizeInBytes: 11920,
          },
          thumbnail: {
            ext: '.webp',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/thumbnail_javasript_f1475e45fe.webp',
            hash: 'thumbnail_javasript_f1475e45fe',
            mime: 'image/webp',
            name: 'thumbnail_javasript.webp',
            path: null,
            size: 2.49,
            width: 245,
            height: 136,
            sizeInBytes: 2490,
          },
        },
        hash: 'javasript_f1475e45fe',
        ext: '.webp',
        mime: 'image/webp',
        size: 23.68,
        url: 'https://special-horn-8ee9415e94.media.strapiapp.com/javasript_f1475e45fe.webp',
        previewUrl: null,
        provider: 'strapi-provider-upload-strapi-cloud',
        provider_metadata: null,
        createdAt: '2025-09-22T09:37:23.157Z',
        updatedAt: '2025-09-22T09:37:23.157Z',
        publishedAt: '2025-09-22T09:37:23.158Z',
      },
      author: {
        id: 2,
        documentId: 'c08gl5796b9a93tfk8ecrg1t',
        username: 'Akmaljon',
        email: 'akmal2002@gmail.com',
        provider: 'local',
        confirmed: true,
        blocked: false,
        createdAt: '2025-09-22T07:25:12.464Z',
        updatedAt: '2025-09-22T07:25:12.464Z',
        publishedAt: '2025-09-22T07:25:12.464Z',
      },
    },
  ],
  meta: {
    pagination: {
      page: 1,
      pageSize: 6,
      pageCount: 2,
      total: 8,
    },
  },
}

export const blogPost = {
  data: [
    {
      id: 1,
      documentId: 'd7a0k4kq4dk925ky6l1i1zlf',
      title: 'How to Improve Your Coding Skills',
      slug: 'how-to-improve-your-coding-skills',
      views: 23,
      description:
        'Here’s a clean, engaging blog post draft for your topic:\n\n---\n\n# How to Improve Your Coding Skills\n\nBecoming a better programmer is a journey, not a one-time achievement. Whether you’re a beginner or already have experience, consistent practice and smart learning strategies will help you grow faster. Here are some effective ways to improve your coding skills:\n\n---\n\n## 1. Code Every Day\n\nConsistency is key. Even 30–60 minutes of daily practice will build your problem-solving muscle and strengthen your understanding.\n👉 Tip: Solve small coding challenges or work on personal mini-projects regularly.\n\n---\n\n## 2. Work on Real Projects\n\nTheory is important, but practical projects teach you more.\n\n* Build apps, websites, or tools.\n* Contribute to open-source projects.\n* Recreate apps you use daily (like a to-do app or weather app).\n\n---\n\n## 3. Read and Understand Other People’s Code\n\nExplore GitHub repositories, tutorials, or open-source projects. Reading other developers’ code exposes you to new patterns, techniques, and problem-solving styles.\n\n---\n\n## 4. Learn Data Structures and Algorithms\n\nStrong fundamentals make you a more effective developer.\n\n* Start with arrays, objects, linked lists, and trees.\n* Practice algorithm problems on platforms like LeetCode, Codeforces, or HackerRank.\n\n---\n\n## 5. Participate in Coding Challenges\n\nJoin coding competitions and hackathons. They improve your speed, problem-solving, and teamwork skills under pressure.\n\n---\n\n## 6. Write Clean and Readable Code\n\nGood code isn’t just about solving problems—it’s about writing solutions others (and your future self) can understand.\n\n* Use meaningful variable names.\n* Add comments only where necessary.\n* Follow consistent formatting.\n\n---\n\n## 7. Keep Learning New Tools and Frameworks\n\nThe tech world evolves quickly. Stay updated by exploring new libraries, frameworks, and technologies relevant to your field (like React, Next.js, or Node.js for web developers).\n\n---\n\n## 8. Ask for Feedback and Do Code Reviews\n\nFeedback from experienced developers is priceless. Participate in code reviews, share your work, and learn from the mistakes others point out.\n\n---\n\n## 9. Teach What You Learn\n\nExplaining concepts to others (via blogs, videos, or mentoring) reinforces your knowledge and helps you discover gaps in your understanding.\n\n---\n\n## 10. Be Patient and Persistent\n\nImproving coding skills takes time. Don’t get discouraged if you don’t understand something right away. Every bug you fix and every project you complete makes you better.\n\n---\n\n✅ **Conclusion:**\nImproving your coding skills is about consistency, practice, and curiosity. Start small, keep building, learn from others, and never stop experimenting.\n\n---\n\nDo you want me to make this blog **short and motivational** (for beginners) or **longer with technical resources/links** for deeper learning?\n',
      createdAt: '2025-09-22T05:43:12.018Z',
      updatedAt: '2025-09-22T05:43:12.018Z',
      publishedAt: '2025-09-22T05:43:11.855Z',
      image: {
        id: 1,
        documentId: 'b5uyx6wh3lghvki6jczowshz',
        name: 'maxresdefault.jpg',
        alternativeText: null,
        caption: null,
        width: 1280,
        height: 720,
        formats: {
          large: {
            ext: '.jpg',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/large_maxresdefault_2524dd2e42.jpg',
            hash: 'large_maxresdefault_2524dd2e42',
            mime: 'image/jpeg',
            name: 'large_maxresdefault.jpg',
            path: null,
            size: 73.25,
            width: 1000,
            height: 563,
            sizeInBytes: 73246,
          },
          small: {
            ext: '.jpg',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/small_maxresdefault_2524dd2e42.jpg',
            hash: 'small_maxresdefault_2524dd2e42',
            mime: 'image/jpeg',
            name: 'small_maxresdefault.jpg',
            path: null,
            size: 28.54,
            width: 500,
            height: 281,
            sizeInBytes: 28540,
          },
          medium: {
            ext: '.jpg',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/medium_maxresdefault_2524dd2e42.jpg',
            hash: 'medium_maxresdefault_2524dd2e42',
            mime: 'image/jpeg',
            name: 'medium_maxresdefault.jpg',
            path: null,
            size: 50.17,
            width: 750,
            height: 422,
            sizeInBytes: 50171,
          },
          thumbnail: {
            ext: '.jpg',
            url: 'https://special-horn-8ee9415e94.media.strapiapp.com/thumbnail_maxresdefault_2524dd2e42.jpg',
            hash: 'thumbnail_maxresdefault_2524dd2e42',
            mime: 'image/jpeg',
            name: 'thumbnail_maxresdefault.jpg',
            path: null,
            size: 10.23,
            width: 245,
            height: 138,
            sizeInBytes: 10227,
          },
        },
        hash: 'maxresdefault_2524dd2e42',
        ext: '.jpg',
        mime: 'image/jpeg',
        size: 94.59,
        url: 'https://special-horn-8ee9415e94.media.strapiapp.com/maxresdefault_2524dd2e42.jpg',
        previewUrl: null,
        provider: 'strapi-provider-upload-strapi-cloud',
        provider_metadata: null,
        createdAt: '2025-09-22T05:40:44.145Z',
        updatedAt: '2025-09-22T05:40:44.145Z',
        publishedAt: '2025-09-22T05:40:44.146Z',
      },
      author: {
        id: 1,
        documentId: 'ngl6xuhuzhwbszhud7n42aym',
        username: 'Jamshid',
        email: 'jamshid2002@gamil.com',
        provider: 'local',
        confirmed: true,
        blocked: false,
        createdAt: '2025-09-22T05:41:50.458Z',
        updatedAt: '2025-09-22T07:00:22.885Z',
        publishedAt: '2025-09-22T07:00:22.642Z',
      },
    }
  ],
  meta: {
    pagination: {
      page: 1,
      pageSize: 6,
      pageCount: 2,
      total: 8,
    },
  },
}
